export const releases = [
  {
    version: '0.1.0-beta.4',
    published: '2026-10-10',
    summary: '新增 Apple 备忘录导入，完善 iCloud 日历同步与重复事件编辑，优化更新提示和笔记体验。',
    summaryEn: 'Import Apple Notes, improve iCloud calendar sync and repeating events, and enjoy a refreshed update prompt and note editor.',
    items: [
      '支持导入 Apple 备忘录：在设置中选择 Apple 备忘录库，将笔记导入 Void。',
      'iCloud 日历新增“重新导入”按钮：清除 Void 本地保存的 iCloud 数据并重新导入，不会修改 iCloud 中的数据。',
      '编辑或删除 iCloud 重复事件时，可选择“仅此事件”或“所有事件”；关闭编辑器时会自动询问。',
      '启动后 5 秒内检查新版本；重新设计更新提示，可选择以后自动下载，或不再显示提示。',
      '每个 iCloud 日历显示自己的颜色，事件色边始终使用日历颜色，在 Void 中选择的颜色只影响事件背景。',
      '删除关联 iCloud、Google 或 Outlook 的事件时立即移除；删除失败会恢复事件并说明原因。',
      '写入 iCloud 的事件使用本地时区，避免 Apple 日历显示额外的 GMT 时间；旧事件下次在 Void 编辑时会修正。',
      '加快大型 iCloud 日历的读取，提高可靠性。',
      '右键点击 Island 可打开设置或退出 Void，收起动画更流畅；AI 面板的模型选择菜单焕新。',
      '修复在 Void 创建的事件未同步到 iCloud 的问题；此前同步失败的事件会在下次成功同步后自动重试。',
      '修复移动 Apple 日历事件到其他日历或重命名时出现“重复事件”错误的问题。',
      '修复 iCloud 同步覆盖自选事件颜色的问题，移除选中事件上下方的蓝线。',
      '修复笔记编辑器跨块选择、撤销与重做、删除清单行及折叠缩进笔记的问题。',
      '移除两篇过时的入门示例笔记，保留已编辑过的笔记；聊天标题栏更紧凑，并更新 Discord 社区链接。',
    ],
    itemsEn: [
      'Import from Apple Notes: choose an Apple Notes library in Settings to bring your notes into Void.',
      'Re-import iCloud Calendar: a new button clears iCloud data kept locally in Void and imports it again, without changing anything in iCloud.',
      'Edit or delete repeating iCloud events with a choice of This event or All events, shown automatically when you close the editor.',
      'Check for a new version within 5 seconds of opening. The redesigned update prompt lets you choose automatic downloads in the future or stop seeing the prompt.',
      'Each iCloud calendar shows its own color. Event accent bars always use the calendar color; a color picked in Void changes only the event background.',
      'Deleting events linked to iCloud, Google or Outlook removes them immediately. If deletion fails, the event returns with an explanation.',
      'Events written to iCloud use your local time zone, avoiding extra GMT times in Apple Calendar. Older events are corrected the next time you edit them in Void.',
      'Reading large iCloud calendars is faster and more reliable.',
      'Right-click the Island to open settings or quit Void, with smoother collapsing animation and a refreshed AI model menu.',
      'Fixed events created in Void not reaching iCloud. Earlier sync failures retry automatically after the next successful sync.',
      'Moving Apple Calendar events to another calendar or renaming them no longer fails with repeating-event errors.',
      'Colors picked for iCloud events survive syncing, and selected events no longer show blue lines above and below them.',
      'Fixed note editor issues with cross-block text selection, undo and redo, deleting checklist rows, and collapsing indented notes.',
      'Removed two outdated getting-started demo notes while keeping edited notes, made the chat header more compact, and updated the Discord community link.',
    ],
    notes: [
      '重新导入 iCloud 会在本地移除由 Void 创建并关联 iCloud 的事件，以及它们的任务关联、颜色和提醒；iCloud 中的副本会作为普通 iCloud 事件重新导入。',
    ],
    notesEn: [
      'Re-importing iCloud removes events created in Void and linked to iCloud locally, along with their task links, colors and reminders. Their iCloud copies return as regular iCloud events.',
    ],
  },
  {
    version: '0.1.0-beta.3',
    published: '2026-10-09',
    summary: '默认开启 Void Island 与会议提醒，优化月视图并修复 macOS 图标。',
    summaryEn: 'Void Island and meeting reminders are now on by default, with an improved month view and a fix for the macOS app icon.',
    items: [
      'Void Island 默认开启：悬停在刘海区域即可打开任务地图、专注计时器、日记和像素猫；开启时播放简短的像素音效，可在设置 → Island 中关闭。',
      '会议提醒默认开启：首次启动时请求 macOS 通知权限，在会议开始前 5 分钟和结束时提醒；拒绝权限后自动关闭，可在设置中重新开启。',
      'Void Island 支持英语，按钮、消息和像素猫语录跟随应用语言。',
      'Island 设置中的悬停延迟、宽度与音量滑块更长，并新增数值输入框以便精确调整。',
      '月视图使用与周视图一致的浅色背景和色边事件卡片，每天可容纳更多事件，修复最后一行被裁切的问题。',
      '修复 macOS 26 之前的系统上应用图标显示为白色方块，以及英文模式下 Void Island 仍显示中文的问题。',
    ],
    itemsEn: [
      'Void Island is on by default. Hover over your notch to open your task map, focus timer, journal and pixel cat. A short pixel jingle plays when it turns on; you can turn it off in Settings → Island.',
      'Meeting reminders are on by default. On first launch, the app asks for macOS notification permission and reminds you 5 minutes before meetings and when they end. Declining permission switches reminders off; you can turn them on again in Settings.',
      'Void Island now supports English: buttons, messages and the cat’s quotes follow the app language.',
      'Island settings have longer hover delay, width and volume sliders, with number fields for exact values.',
      'Month view uses the same tinted event cards with colored edges as week view, fits more events per day, and no longer cuts off the last row.',
      'Fixed the white square app icon on macOS versions before macOS 26, and Chinese text appearing in Void Island when the app was set to English.',
    ],
    notes: [
      '升级后，Void Island 和会议提醒会开启一次，即使之前已关闭；如不需要，请在设置中再次关闭，此后会保留你的选择。',
      '如果 Dock 或启动台仍显示方块图标，这是 macOS 缓存了旧图标，可运行 killall Dock 刷新。',
    ],
    notesEn: [
      'Void Island and meeting reminders are switched on once after this update, even if you had turned them off before. Turn them off again in Settings if you prefer; your choice is kept from then on.',
      'If Dock or Launchpad still shows a square icon, macOS is caching the old one. Run killall Dock to refresh it.',
    ],
  },
  {
    version: '0.1.0-beta.2',
    published: '2026-10-08',
    summary: '优化 macOS 桌面体验，移除浏览器默认右键菜单。',
    summaryEn: 'This update improves the macOS desktop experience by removing browser-specific right-click menus.',
    items: [
      '禁用正式桌面构建中的默认 WebView 右键菜单，移除查询、翻译、搜索、共享、语音和服务等操作。',
      '保留 Void Calendar 自身的右键菜单，以及复制和粘贴的键盘快捷键。',
    ],
    itemsEn: [
      'Disabled the default WebView context menu in production desktop builds, removing actions such as Look Up, Translate, Search, Share, Speech, and Services.',
      'Preserved Void Calendar’s own right-click menus and keyboard shortcuts for copying and pasting.',
    ],
    notes: [
      '网页和开发构建仍保留默认右键菜单。',
      '这是测试版，欢迎反馈使用中遇到的问题。',
    ],
    notesEn: [
      'Web and development builds retain their default context menus.',
      'This is a beta release. Please report any issues you encounter.',
    ],
  },
  {
    version: '0.1.0-beta.1',
    published: '2026-10-08',
    summary: 'Void Calendar 是一款本地优先的日历与项目排程应用，主要为 macOS 打造。',
    summaryEn: 'Void Calendar is a local-first calendar and project scheduling app built primarily for macOS.',
    items: [
      '日历与任务：管理事件、项目和待办事项，并将任务安排到时间块中。',
      '笔记：记录灵感和每日笔记，并在笔记与任务之间建立关联。',
      'AI 辅助：规划日程和修改事件，支持操作历史与撤销。',
      '日历集成：连接 Apple 日历、Apple 提醒事项、Google 日历、Outlook 和 CalDAV 服务。',
      'macOS 体验：使用菜单栏工具、灵动岛功能和通知。',
      '语言：在英语与简体中文之间切换。',
      '应用内更新：检查更新、下载签名安装包，并在保存工作后重启安装。',
    ],
    itemsEn: [
      'Calendar and tasks: Organize events, projects, and to-dos, and schedule tasks into time blocks.',
      'Notes: Capture ideas and daily notes, with links between notes and tasks.',
      'AI assistance: Plan your schedule and modify events with operation history and undo support.',
      'Calendar integrations: Connect Apple Calendar, Apple Reminders, Google Calendar, Outlook, and CalDAV services.',
      'macOS experience: Access menu bar tools, Dynamic Island features, and notifications.',
      'Languages: Switch between English and Simplified Chinese.',
      'In-app updates: Check for updates, download signed packages, and restart to install after saving your work.',
    ],
    notes: [
      '可用的集成取决于账户配置和权限。',
      '账户与云同步需要配置后端。',
      '自动更新分发需要已发布且经过签名的更新包。',
    ],
    notesEn: [
      'Available integrations depend on account configuration and permissions.',
      'Account and cloud synchronization require a configured backend.',
      'Automatic update delivery requires a published, signed update package.',
    ],
  },
]
