export const comparisons = [
  {
    slug: 'void-calendar-vs-notion',
    product: 'Notion',
    title: 'Void Calendar vs Notion：日历里的任务，也是一页笔记',
    titleEn: 'Void Calendar vs Notion: A calendar task is also a page of notes',
    description: '提前写下怎么开始，做的时候留下记录，再让 AI 把笔记变成任务、安排时间。',
    descriptionEn: 'Write down how to start, keep what you learn, and let AI turn your notes into scheduled work.',
  },
  {
    slug: 'void-calendar-vs-motion',
    product: 'Motion',
    title: 'Void Calendar vs Motion：排好的一周，周三就变了',
    titleEn: 'Void Calendar vs Motion: The week was planned, then Wednesday changed',
    description: 'AI 能重新排时间，我还希望任务的步骤、资料和上次的记录都能跟着走。',
    descriptionEn: 'AI can reschedule time. I also want the steps, material, and previous records to come along.',
  },
  {
    slug: 'void-calendar-vs-morgen',
    product: 'Morgen',
    title: 'Void Calendar vs Morgen：日历合到一起，任务内容放在哪里？',
    titleEn: 'Void Calendar vs Morgen: Calendars together, but where does the context go?',
    description: '看全今天的安排很重要。到了要做的时候，我还想直接找到资料、步骤和反馈。',
    descriptionEn: 'Seeing the whole day matters. Starting work also needs the material, steps, and feedback.',
  },
  {
    slug: 'void-calendar-vs-ticktick',
    product: 'TickTick',
    title: 'Void Calendar vs TickTick：做完这一步，下一步怎样接上？',
    titleEn: 'Void Calendar vs TickTick: Finish one step, then move to the next',
    description: '任务依赖图看清先后顺序，让 AI 安排时间，再通过插件把工作交给 AI。',
    descriptionEn: 'See task dependencies, plan time with your AI, and hand work over through plugins.',
  },
  {
    slug: 'void-calendar-vs-google-tasks',
    product: 'Google Tasks',
    title: 'Void Calendar vs Google Tasks：“准备雅思”四个字，怎么开始？',
    titleEn: 'Void Calendar vs Google Tasks: “Prepare for IELTS” still needs a starting point',
    description: '随手记一条很方便。任务变大以后，还要有地方放练习步骤、资料和错题。',
    descriptionEn: 'Quick capture is useful. Larger tasks need room for instructions, material, and mistakes.',
  },
  {
    slug: 'void-calendar-vs-todoist',
    product: 'Todoist',
    title: 'Void Calendar vs Todoist：清单整理好了，今天还是装不下',
    titleEn: 'Void Calendar vs Todoist: An organized list can still overfill today',
    description: '捕捉要轻，执行要清楚。聊聊清单、课程报告，以及任务背后的笔记。',
    descriptionEn: 'Keep capture light and execution clear. Lists, course reports, and the notes behind the work.',
  },
  {
    slug: 'void-calendar-vs-microsoft-to-do',
    product: 'Microsoft To Do',
    title: 'Void Calendar vs Microsoft To Do：选好了重点，今天还剩多少时间？',
    titleEn: 'Void Calendar vs Microsoft To Do: Priorities picked, how much time is left?',
    description: '我喜欢 My Day 的轻巧，也希望大任务能拆成今天确实做得完的一小步。',
    descriptionEn: 'I like My Day’s lightness, and want large tasks to become steps that fit today.',
  },
  {
    slug: 'void-calendar-vs-trello',
    product: 'Trello',
    title: 'Void Calendar vs Trello：卡片挪到“进行中”，今天有空做吗？',
    titleEn: 'Void Calendar vs Trello: The card is in progress, but is there time today?',
    description: '看板能让团队看见进度。我还想把自己的步骤、笔记和一天的时间接起来。',
    descriptionEn: 'A board shares progress. I also want my steps, notes, and working time connected.',
  },
  {
    slug: 'void-calendar-vs-omnifocus',
    product: 'OmniFocus',
    title: 'Void Calendar vs OmniFocus：几百个念头，把我的 Inbox 堵住了',
    titleEn: 'Void Calendar vs OmniFocus: Hundreds of thoughts clogged my Inbox',
    description: '我用 OmniFocus 管理复杂任务，却被尚未成为任务的念头堵住了。Void Calendar 从 Idea 开始。',
    descriptionEn: 'OmniFocus helped with complex work, but uncommitted thoughts filled my Inbox. Void Calendar starts with Idea.',
  },
  {
    slug: 'void-calendar-vs-things-3',
    product: 'Things 3',
    title: 'Void Calendar vs Things 3：我喜欢它的简单，也需要更完整的笔记',
    titleEn: 'Void Calendar vs Things 3: I like its simplicity, and need fuller notes',
    description: '轻量任务我一直放在 Things 3。但任务背后的资料、心得和踩过的坑，我希望也能留下来。',
    descriptionEn: 'My lightweight tasks stay in Things 3. I also want to keep the context, lessons, and mistakes behind the work.',
  },
  {
    slug: 'void-calendar-vs-org-mode',
    product: 'Org mode',
    title: 'Void Calendar vs Org mode：强大之外，我也想少折腾一点',
    titleEn: 'Void Calendar vs Org mode: Powerful tools, less setup',
    description: '我用过 Org mode，也写过复杂配置。聊聊同步、手机使用，以及后来转向 OmniFocus 的经历。',
    descriptionEn: 'My experience with Org mode configuration, synchronization, mobile use, and moving to OmniFocus.',
  },
  {
    slug: 'void-calendar-vs-obsidian-tasks',
    product: 'Obsidian Tasks',
    title: 'Void Calendar vs Obsidian Tasks：查询找到了任务，什么时候做？',
    titleEn: 'Void Calendar vs Obsidian Tasks: The query found the work, when will it happen?',
    description: '在笔记里顺手记任务很自然。查询把它们找出来以后，还要给执行留时间。',
    descriptionEn: 'Capture tasks where the thought occurs. After a query finds them, reserve time to do them.',
  },
] as const
