/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnChangelogRouteImport } from './routes/en/changelog'
import { Route as EnPricingRouteImport } from './routes/en/pricing'
import { Route as EnPrivacyRouteImport } from './routes/en/privacy'
import { Route as EnTermsRouteImport } from './routes/en/terms'
import { Route as UpdatesStableDotjsonRouteImport } from './routes/updates.stable[.]json'
import { Route as EnBlogIndexRouteImport } from './routes/en/blog/index'
import { Route as EnBlogSlugRouteImport } from './routes/en/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnChangelogRoute = EnChangelogRouteImport.update({
  id: '/en/changelog',
  path: '/en/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPricingRoute = EnPricingRouteImport.update({
  id: '/en/pricing',
  path: '/en/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/en/terms',
  path: '/en/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesStableDotjsonRoute = UpdatesStableDotjsonRouteImport.update({
  id: '/updates/stable.json',
  path: '/updates/stable.json',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogIndexRoute = EnBlogIndexRouteImport.update({
  id: '/en/blog/',
  path: '/en/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/en/blog/$slug',
  path: '/en/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/changelog': typeof EnChangelogRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/updates/stable.json': typeof UpdatesStableDotjsonRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/changelog': typeof EnChangelogRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/updates/stable.json': typeof UpdatesStableDotjsonRoute
  '/blog': typeof BlogIndexRoute
  '/en': typeof EnIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog': typeof EnBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/en/changelog': typeof EnChangelogRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/updates/stable.json': typeof UpdatesStableDotjsonRoute
  '/blog/': typeof BlogIndexRoute
  '/en/': typeof EnIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/blog/': typeof EnBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/en/changelog'
    | '/en/pricing'
    | '/en/privacy'
    | '/en/terms'
    | '/updates/stable.json'
    | '/blog/'
    | '/en/'
    | '/en/blog/$slug'
    | '/en/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/en/changelog'
    | '/en/pricing'
    | '/en/privacy'
    | '/en/terms'
    | '/updates/stable.json'
    | '/blog'
    | '/en'
    | '/en/blog/$slug'
    | '/en/blog'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/en/changelog'
    | '/en/pricing'
    | '/en/privacy'
    | '/en/terms'
    | '/updates/stable.json'
    | '/blog/'
    | '/en/'
    | '/en/blog/$slug'
    | '/en/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EnChangelogRoute: typeof EnChangelogRoute
  EnPricingRoute: typeof EnPricingRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnTermsRoute: typeof EnTermsRoute
  UpdatesStableDotjsonRoute: typeof UpdatesStableDotjsonRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  EnBlogSlugRoute: typeof EnBlogSlugRoute
  EnBlogIndexRoute: typeof EnBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/changelog': {
      id: '/en/changelog'
      path: '/en/changelog'
      fullPath: '/en/changelog'
      preLoaderRoute: typeof EnChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pricing': {
      id: '/en/pricing'
      path: '/en/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof EnPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/en/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates/stable.json': {
      id: '/updates/stable.json'
      path: '/updates/stable.json'
      fullPath: '/updates/stable.json'
      preLoaderRoute: typeof UpdatesStableDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/': {
      id: '/en/blog/'
      path: '/en/blog'
      fullPath: '/en/blog/'
      preLoaderRoute: typeof EnBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/en/blog/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  EnChangelogRoute: EnChangelogRoute,
  EnPricingRoute: EnPricingRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnTermsRoute: EnTermsRoute,
  UpdatesStableDotjsonRoute: UpdatesStableDotjsonRoute,
  BlogIndexRoute: BlogIndexRoute,
  EnIndexRoute: EnIndexRoute,
  EnBlogSlugRoute: EnBlogSlugRoute,
  EnBlogIndexRoute: EnBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
